apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ipoint-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/MadhavManatar/argocdtest.git
    targetRevision: HEAD
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: ipoint-dev

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true